"""集中登记 OAKOC 变量和可使用的公开数据来源。

目录会明确写出一个来源能提供什么、不能提供什么。公开数据只能作为原始数据
或近似参考，不能直接当成“可以通行”“可以观察”“能够掩蔽”或“属于关键地形”
等分析结论。
"""

from datetime import date

from .models import (
    AccessMethod,
    Accessibility,
    AcquisitionMode,
    DataRole,
    ImpactLevel,
    ImplementationPriority,
    MissingPolicy,
    QualityRequirement,
    RequirementLevel,
    SourceSpec,
    StageId,
    ValueType,
    VariableSpec,
    VerificationStatus,
)


# 修改变量含义或来源映射时应更新此版本，让运行结果能说明使用了哪版目录。
CATALOG_VERSION = "2026.09-mvp1"


def _quality(
    coverage: float | None = None,
    resolution_m: float | None = None,
    maximum_age_hours: float | None = None,
    *checks: str,
) -> QualityRequirement:
    """简写变量的覆盖率、分辨率、时效和检查项，避免在目录中重复长代码。"""

    # 没有给出的要求保持为 None，表示目录目前不强制写死该数值。
    return QualityRequirement(
        minimum_coverage_ratio=coverage,
        target_resolution_m=resolution_m,
        maximum_age_hours=maximum_age_hours,
        checks=checks,
    )


def build_variable_catalog() -> tuple[VariableSpec, ...]:
    """返回全流程变量目录，后续表格和对应关系都应从这里自动生成。"""

    # 先建空列表，再按流程步骤分组加入变量，便于按执行顺序阅读。
    variables: list[VariableSpec] = []

    # 第 1 步：任务侧上下文决定本次分析需要哪些数据和参数。
    # 第一个变量完整展示 VariableSpec 的常用字段，后面的变量使用相同含义：
    # variable_id 是程序编号，name_zh 和 description 是中文名称与解释；
    # stage、data_role、value_type 说明何时出现、承担什么作用、内容是什么类型；
    # requirement_level 和 implementation_priority 分别表示是否必要和开发顺序；
    # accessibility、acquisition_modes、source_priority 说明能否取得以及从哪里取得；
    # result_impact、missing_policies 说明缺少变量的影响和处理办法；
    # quality_requirement 写质量要求，used_by 列出后面会使用它的步骤。
    variables.extend(
        [
            VariableSpec(
                variable_id="context.aoi",
                name_zh="分析区域",
                description="本次 OAKOC 计算和成果裁剪使用的空间边界引用。",
                stage=StageId.CONTEXT_REQUIREMENTS,
                data_role=DataRole.CONTEXT,
                value_type=ValueType.POLYGON,
                unit=None,
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DIRECT,
                acquisition_modes=(AcquisitionMode.TASK_CONFIG,),
                result_impact=ImpactLevel.HIGH,
                quality_requirement=_quality(None, None, None, "valid_geometry", "declared_crs"),
                missing_policies=(MissingPolicy.BLOCK,),
                used_by=tuple(StageId),
            ),
            VariableSpec(
                variable_id="context.time_window",
                name_zh="分析时间窗",
                description="数据筛选、动态条件和结果有效期共同使用的时间范围。",
                stage=StageId.CONTEXT_REQUIREMENTS,
                data_role=DataRole.CONTEXT,
                value_type=ValueType.TIME_RANGE,
                unit=None,
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DIRECT,
                acquisition_modes=(AcquisitionMode.TASK_CONFIG,),
                result_impact=ImpactLevel.HIGH,
                quality_requirement=_quality(None, None, None, "valid_time_order"),
                missing_policies=(MissingPolicy.REQUIRE_TASK_INPUT, MissingPolicy.BLOCK),
                used_by=tuple(StageId),
            ),
            VariableSpec(
                variable_id="context.analysis_perspective",
                name_zh="分析视角",
                description="所有地形效果和综合判断所适用的主体或阵营标识。",
                stage=StageId.CONTEXT_REQUIREMENTS,
                data_role=DataRole.CONTEXT,
                value_type=ValueType.REFERENCE,
                unit=None,
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DIRECT,
                acquisition_modes=(AcquisitionMode.TASK_CONFIG,),
                result_impact=ImpactLevel.HIGH,
                missing_policies=(MissingPolicy.REQUIRE_TASK_INPUT, MissingPolicy.BLOCK),
                used_by=(
                    StageId.ANALYSIS_OBSTACLES,
                    StageId.ANALYSIS_OBSERVATION_AND_FIRE,
                    StageId.ANALYSIS_COVER_AND_CONCEALMENT,
                    StageId.ANALYSIS_KEY_TERRAIN_CANDIDATES,
                    StageId.ANALYSIS_APPROACH_ROUTES,
                    StageId.ANALYSIS_KEY_TERRAIN_REVIEW,
                    StageId.PUBLISH_VALIDATE_AND_RELEASE,
                ),
            ),
            VariableSpec(
                variable_id="context.mission_phase",
                name_zh="任务阶段",
                description="用于解释路线、时机和关键地形相关性的任务阶段。",
                stage=StageId.CONTEXT_REQUIREMENTS,
                data_role=DataRole.CONTEXT,
                value_type=ValueType.ENUM,
                unit=None,
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DIRECT,
                acquisition_modes=(AcquisitionMode.TASK_CONFIG,),
                result_impact=ImpactLevel.HIGH,
                missing_policies=(MissingPolicy.REQUIRE_TASK_INPUT,),
                used_by=(
                    StageId.ANALYSIS_KEY_TERRAIN_CANDIDATES,
                    StageId.ANALYSIS_APPROACH_ROUTES,
                    StageId.ANALYSIS_KEY_TERRAIN_REVIEW,
                ),
            ),
            VariableSpec(
                variable_id="context.mission_objective",
                name_zh="任务目的",
                description="候选关键地形和路线效果需要支持的任务结果。",
                stage=StageId.CONTEXT_REQUIREMENTS,
                data_role=DataRole.CONTEXT,
                value_type=ValueType.OBJECT,
                unit=None,
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DIRECT,
                acquisition_modes=(AcquisitionMode.TASK_CONFIG,),
                result_impact=ImpactLevel.HIGH,
                missing_policies=(MissingPolicy.REQUIRE_TASK_INPUT,),
                used_by=(
                    StageId.ANALYSIS_KEY_TERRAIN_CANDIDATES,
                    StageId.ANALYSIS_APPROACH_ROUTES,
                    StageId.ANALYSIS_KEY_TERRAIN_REVIEW,
                ),
            ),
            VariableSpec(
                variable_id="context.effect_criteria",
                name_zh="任务效果判据",
                description="判断地形控制效果是否与任务相关的可验证条件集合。",
                stage=StageId.CONTEXT_REQUIREMENTS,
                data_role=DataRole.CONTEXT,
                value_type=ValueType.ARRAY,
                unit=None,
                requirement_level=RequirementLevel.CONDITIONAL,
                required_when="请求候选关键地形或最终关键地形复核时。",
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DIRECT,
                acquisition_modes=(AcquisitionMode.TASK_CONFIG,),
                result_impact=ImpactLevel.HIGH,
                missing_policies=(MissingPolicy.REQUIRE_TASK_INPUT, MissingPolicy.UNKNOWN),
                used_by=(
                    StageId.ANALYSIS_KEY_TERRAIN_CANDIDATES,
                    StageId.ANALYSIS_KEY_TERRAIN_REVIEW,
                ),
            ),
            VariableSpec(
                variable_id="context.requested_analyses",
                name_zh="请求分析项",
                description="本次任务需要执行和发布的分析节点集合。",
                stage=StageId.CONTEXT_REQUIREMENTS,
                data_role=DataRole.CONTEXT,
                value_type=ValueType.ARRAY,
                unit=None,
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DIRECT,
                acquisition_modes=(AcquisitionMode.TASK_CONFIG,),
                result_impact=ImpactLevel.HIGH,
                missing_policies=(MissingPolicy.REQUIRE_TASK_INPUT,),
                used_by=(StageId.CONTEXT_REQUIREMENTS, StageId.PUBLISH_VALIDATE_AND_RELEASE),
            ),
            VariableSpec(
                variable_id="context.rule_set_ref",
                name_zh="规则集引用",
                description="分析阈值、权重、分类规则和保守默认值的版本化引用。",
                stage=StageId.CONTEXT_REQUIREMENTS,
                data_role=DataRole.PARAMETER,
                value_type=ValueType.REFERENCE,
                unit=None,
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DIRECT,
                acquisition_modes=(AcquisitionMode.TASK_CONFIG,),
                result_impact=ImpactLevel.HIGH,
                missing_policies=(MissingPolicy.BLOCK,),
                used_by=tuple(StageId)[2:],
            ),
            VariableSpec(
                variable_id="parameter.mobility_profile",
                name_zh="机动平台配置",
                description="坡度、地表、道路和跨越条件解释所针对的平台能力版本。",
                stage=StageId.CONTEXT_REQUIREMENTS,
                data_role=DataRole.PARAMETER,
                value_type=ValueType.REFERENCE,
                unit=None,
                requirement_level=RequirementLevel.CONDITIONAL,
                required_when="请求障碍分析或接近路线分析时。",
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DIRECT,
                acquisition_modes=(AcquisitionMode.TASK_CONFIG,),
                result_impact=ImpactLevel.HIGH,
                missing_policies=(MissingPolicy.REQUIRE_TASK_INPUT, MissingPolicy.BLOCK),
                used_by=(StageId.ANALYSIS_OBSTACLES, StageId.ANALYSIS_APPROACH_ROUTES),
            ),
            VariableSpec(
                variable_id="parameter.sensor_profile",
                name_zh="观察传感器配置",
                description="观察高度、量程、探测条件和目标特征等版本化能力参数。",
                stage=StageId.CONTEXT_REQUIREMENTS,
                data_role=DataRole.PARAMETER,
                value_type=ValueType.REFERENCE,
                unit=None,
                requirement_level=RequirementLevel.CONDITIONAL,
                required_when="请求观察分析或威胁相关隐蔽分析时。",
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DIRECT,
                acquisition_modes=(AcquisitionMode.TASK_CONFIG,),
                result_impact=ImpactLevel.HIGH,
                missing_policies=(MissingPolicy.REQUIRE_TASK_INPUT, MissingPolicy.UNKNOWN),
                used_by=(
                    StageId.ANALYSIS_OBSERVATION_AND_FIRE,
                    StageId.ANALYSIS_COVER_AND_CONCEALMENT,
                ),
            ),
            VariableSpec(
                variable_id="parameter.fire_profile",
                name_zh="火力能力配置",
                description="射程、作用对象和几何限制等版本化参数，不由公开地形数据推断。",
                stage=StageId.CONTEXT_REQUIREMENTS,
                data_role=DataRole.PARAMETER,
                value_type=ValueType.REFERENCE,
                unit=None,
                requirement_level=RequirementLevel.CONDITIONAL,
                required_when="请求射界或火力相关掩蔽分析时。",
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.UNAVAILABLE,
                acquisition_modes=(AcquisitionMode.TASK_CONFIG,),
                result_impact=ImpactLevel.HIGH,
                missing_policies=(MissingPolicy.REQUIRE_TASK_INPUT, MissingPolicy.UNKNOWN),
                used_by=(
                    StageId.ANALYSIS_OBSERVATION_AND_FIRE,
                    StageId.ANALYSIS_COVER_AND_CONCEALMENT,
                ),
            ),
            VariableSpec(
                variable_id="context.route_terminals",
                name_zh="路线起终区域",
                description="接近路线搜索必须连接的起点、终点或目标区域引用。",
                stage=StageId.CONTEXT_REQUIREMENTS,
                data_role=DataRole.CONTEXT,
                value_type=ValueType.ARRAY,
                unit=None,
                requirement_level=RequirementLevel.CONDITIONAL,
                required_when="请求接近路线分析时。",
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DIRECT,
                acquisition_modes=(AcquisitionMode.TASK_CONFIG,),
                result_impact=ImpactLevel.HIGH,
                missing_policies=(MissingPolicy.REQUIRE_TASK_INPUT, MissingPolicy.BLOCK),
                used_by=(StageId.ANALYSIS_APPROACH_ROUTES,),
            ),
            VariableSpec(
                variable_id="context.task_constraints",
                name_zh="任务限制条件",
                description="禁止区、时间限制和资源约束等任务侧补充条件。",
                stage=StageId.CONTEXT_REQUIREMENTS,
                data_role=DataRole.CONTEXT,
                value_type=ValueType.ARRAY,
                unit=None,
                requirement_level=RequirementLevel.OPTIONAL,
                implementation_priority=ImplementationPriority.P1,
                accessibility=Accessibility.DIRECT,
                acquisition_modes=(AcquisitionMode.TASK_CONFIG,),
                result_impact=ImpactLevel.MEDIUM,
                missing_policies=(MissingPolicy.UNKNOWN,),
                used_by=(StageId.ANALYSIS_APPROACH_ROUTES, StageId.PUBLISH_VALIDATE_AND_RELEASE),
            ),
            VariableSpec(
                variable_id="parameter.target_crs",
                name_zh="目标坐标参考系",
                description="统一空间运算使用的坐标参考系标识。",
                stage=StageId.CONTEXT_REQUIREMENTS,
                data_role=DataRole.PARAMETER,
                value_type=ValueType.STRING,
                unit=None,
                requirement_level=RequirementLevel.OPTIONAL,
                implementation_priority=ImplementationPriority.P1,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.TASK_CONFIG, AcquisitionMode.PUBLIC_DERIVED),
                result_impact=ImpactLevel.MEDIUM,
                depends_on=("context.aoi",),
                derivation="按 AOI 范围和运算类型选择适用 CRS，并记录选择规则。",
                quality_requirement=_quality(None, None, None, "crs_resolvable"),
                missing_policies=(MissingPolicy.ESTIMATE,),
                used_by=(StageId.DATA_NORMALIZE, StageId.DATA_QUALITY_AND_DERIVE),
            ),
            VariableSpec(
                variable_id="parameter.analysis_resolution",
                name_zh="目标分析分辨率",
                description="统一栅格和派生结果使用的目标像元大小。",
                stage=StageId.CONTEXT_REQUIREMENTS,
                data_role=DataRole.PARAMETER,
                value_type=ValueType.FLOAT,
                unit="m",
                requirement_level=RequirementLevel.OPTIONAL,
                implementation_priority=ImplementationPriority.P1,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.TASK_CONFIG, AcquisitionMode.PUBLIC_DERIVED),
                result_impact=ImpactLevel.MEDIUM,
                derivation="根据 AOI 尺度、规则集和最弱必要输入分辨率确定，不做虚假上采样。",
                missing_policies=(MissingPolicy.ESTIMATE,),
                used_by=(StageId.DATA_NORMALIZE, StageId.DATA_QUALITY_AND_DERIVE),
            ),
        ]
    )

    # 第 2 步：公开服务只提供可计算的原始数据，当前状态优先来自任务或现场记录。
    variables.extend(
        [
            VariableSpec(
                variable_id="raster.elevation",
                name_zh="地表高程栅格",
                description="相对统一垂直基准的地面高程，是坡度和几何视线的基础输入。",
                stage=StageId.DATA_ACQUIRE,
                data_role=DataRole.RASTER,
                value_type=ValueType.RASTER,
                unit="m",
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DIRECT,
                acquisition_modes=(AcquisitionMode.PUBLIC_DIRECT,),
                result_impact=ImpactLevel.HIGH,
                source_priority=("copernicus.dem.glo30",),
                source_fields={"copernicus.dem.glo30": "elevation band; exact asset selector pending adapter verification"},
                quality_requirement=_quality(0.99, 30, None, "declared_crs", "vertical_reference", "nodata"),
                missing_policies=(MissingPolicy.MASK, MissingPolicy.BLOCK),
                used_by=(StageId.DATA_QUALITY_AND_DERIVE,),
            ),
            VariableSpec(
                variable_id="raster.land_cover",
                name_zh="土地覆盖栅格",
                description="地表覆盖类别，用于地表阻力、植被和建设区代理派生。",
                stage=StageId.DATA_ACQUIRE,
                data_role=DataRole.RASTER,
                value_type=ValueType.RASTER,
                unit="class_code",
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DIRECT,
                acquisition_modes=(AcquisitionMode.PUBLIC_DIRECT,),
                result_impact=ImpactLevel.HIGH,
                source_priority=("esa.worldcover.2021",),
                source_fields={"esa.worldcover.2021": "Map classification band"},
                quality_requirement=_quality(0.99, 10, None, "class_legend", "nodata", "product_year"),
                missing_policies=(MissingPolicy.MASK, MissingPolicy.BLOCK),
                used_by=(StageId.DATA_QUALITY_AND_DERIVE,),
            ),
            VariableSpec(
                variable_id="entity.transport_network",
                name_zh="交通网络",
                description="道路、轨道、路径、桥隧和路口等带来源标签的线性网络。",
                stage=StageId.DATA_ACQUIRE,
                data_role=DataRole.ENTITY,
                value_type=ValueType.LINE,
                unit=None,
                requirement_level=RequirementLevel.CONDITIONAL,
                required_when="请求陆上障碍或接近路线分析时。",
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DIRECT,
                acquisition_modes=(AcquisitionMode.PUBLIC_DIRECT, AcquisitionMode.HYBRID),
                result_impact=ImpactLevel.HIGH,
                source_priority=("osm.overpass", "osm.geofabrik"),
                source_fields={"osm.overpass": "highway, railway, bridge, tunnel and related tags"},
                quality_requirement=_quality(None, None, None, "topology", "tag_completeness", "snapshot_time"),
                missing_policies=(MissingPolicy.MASK, MissingPolicy.RECONNAISSANCE_REQUIRED),
                used_by=(StageId.DATA_QUALITY_AND_DERIVE, StageId.ANALYSIS_OBSTACLES),
            ),
            VariableSpec(
                variable_id="entity.buildings",
                name_zh="建筑轮廓",
                description="公开数据中的建筑几何和有限标签，不代表材料或防护能力。",
                stage=StageId.DATA_ACQUIRE,
                data_role=DataRole.ENTITY,
                value_type=ValueType.POLYGON,
                unit=None,
                requirement_level=RequirementLevel.OPTIONAL,
                implementation_priority=ImplementationPriority.P1,
                accessibility=Accessibility.DIRECT,
                acquisition_modes=(AcquisitionMode.PUBLIC_DIRECT, AcquisitionMode.HYBRID),
                result_impact=ImpactLevel.MEDIUM,
                source_priority=("osm.overpass", "osm.geofabrik"),
                source_fields={"osm.overpass": "building, building:levels, height when present"},
                quality_requirement=_quality(None, None, None, "geometry_validity", "tag_completeness"),
                missing_policies=(MissingPolicy.PROXY, MissingPolicy.UNKNOWN),
                used_by=(StageId.DATA_QUALITY_AND_DERIVE,),
            ),
            VariableSpec(
                variable_id="entity.hydrography",
                name_zh="水系与水体对象",
                description="河流、沟渠、湖泊和岸线几何；不包含实时水深和流速。",
                stage=StageId.DATA_ACQUIRE,
                data_role=DataRole.ENTITY,
                value_type=ValueType.OBJECT,
                unit=None,
                requirement_level=RequirementLevel.CONDITIONAL,
                required_when="AOI 存在水系或请求跨水域机动分析时。",
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DIRECT,
                acquisition_modes=(AcquisitionMode.PUBLIC_DIRECT, AcquisitionMode.HYBRID),
                result_impact=ImpactLevel.HIGH,
                source_priority=("osm.overpass", "hydrosheds.hydrorivers"),
                source_fields={"osm.overpass": "waterway, natural=water and water-related tags"},
                quality_requirement=_quality(None, None, None, "geometry_validity", "network_continuity"),
                missing_policies=(MissingPolicy.MASK, MissingPolicy.RECONNAISSANCE_REQUIRED),
                used_by=(StageId.DATA_QUALITY_AND_DERIVE,),
            ),
            VariableSpec(
                variable_id="raster.surface_water_history",
                name_zh="历史地表水栅格",
                description="历史水体出现频率和季节性，用作潜在湿地或水障碍证据。",
                stage=StageId.DATA_ACQUIRE,
                data_role=DataRole.RASTER,
                value_type=ValueType.RASTER,
                unit="percent_or_class",
                requirement_level=RequirementLevel.OPTIONAL,
                implementation_priority=ImplementationPriority.P1,
                accessibility=Accessibility.DIRECT,
                acquisition_modes=(AcquisitionMode.PUBLIC_DIRECT,),
                result_impact=ImpactLevel.MEDIUM,
                source_priority=("jrc.global_surface_water",),
                source_fields={"jrc.global_surface_water": "occurrence, seasonality and change products"},
                quality_requirement=_quality(None, 30, None, "product_version", "observation_count"),
                missing_policies=(MissingPolicy.UNKNOWN,),
                used_by=(StageId.DATA_QUALITY_AND_DERIVE,),
            ),
            VariableSpec(
                variable_id="raster.optical_imagery",
                name_zh="光学遥感影像",
                description="用于覆盖分类核验和地表变化派生的多光谱影像资产。",
                stage=StageId.DATA_ACQUIRE,
                data_role=DataRole.RASTER,
                value_type=ValueType.RASTER,
                unit="reflectance",
                requirement_level=RequirementLevel.OPTIONAL,
                implementation_priority=ImplementationPriority.P1,
                accessibility=Accessibility.DIRECT,
                acquisition_modes=(AcquisitionMode.PUBLIC_DIRECT,),
                result_impact=ImpactLevel.MEDIUM,
                source_priority=("copernicus.sentinel2.l2a",),
                source_fields={"copernicus.sentinel2.l2a": "surface reflectance bands and scene classification"},
                quality_requirement=_quality(None, 10, None, "cloud_mask", "acquisition_time", "processing_level"),
                missing_policies=(MissingPolicy.UNKNOWN,),
                used_by=(StageId.DATA_QUALITY_AND_DERIVE,),
            ),
            VariableSpec(
                variable_id="raster.sar_imagery",
                name_zh="合成孔径雷达影像",
                description="用于云下地表变化和积水代理派生的雷达影像资产。",
                stage=StageId.DATA_ACQUIRE,
                data_role=DataRole.RASTER,
                value_type=ValueType.RASTER,
                unit="backscatter",
                requirement_level=RequirementLevel.OPTIONAL,
                implementation_priority=ImplementationPriority.P1,
                accessibility=Accessibility.DIRECT,
                acquisition_modes=(AcquisitionMode.PUBLIC_DIRECT,),
                result_impact=ImpactLevel.MEDIUM,
                source_priority=("copernicus.sentinel1.grd",),
                source_fields={"copernicus.sentinel1.grd": "GRD backscatter assets and acquisition metadata"},
                quality_requirement=_quality(None, None, None, "orbit", "polarization", "acquisition_time"),
                missing_policies=(MissingPolicy.UNKNOWN,),
                used_by=(StageId.DATA_QUALITY_AND_DERIVE,),
            ),
            VariableSpec(
                variable_id="raster.soil_properties",
                name_zh="土壤属性栅格",
                description="公开土壤质地和容重等长期统计属性，只能支持承载条件代理。",
                stage=StageId.DATA_ACQUIRE,
                data_role=DataRole.RASTER,
                value_type=ValueType.RASTER,
                unit="property_specific",
                requirement_level=RequirementLevel.OPTIONAL,
                implementation_priority=ImplementationPriority.P1,
                accessibility=Accessibility.PROXY_ONLY,
                acquisition_modes=(AcquisitionMode.PUBLIC_DIRECT, AcquisitionMode.PUBLIC_DERIVED),
                result_impact=ImpactLevel.MEDIUM,
                source_priority=("isric.soilgrids.2",),
                source_fields={"isric.soilgrids.2": "clay, sand, silt, bdod, cfvo and water-content properties"},
                quality_requirement=_quality(None, 250, None, "depth_interval", "uncertainty_layer"),
                missing_policies=(MissingPolicy.UNKNOWN,),
                used_by=(StageId.DATA_QUALITY_AND_DERIVE,),
            ),
            VariableSpec(
                variable_id="raster.weather_fields",
                name_zh="背景气象场",
                description="降水、温度、风等再分析背景，不代表战术尺度局地实况。",
                stage=StageId.DATA_ACQUIRE,
                data_role=DataRole.RASTER,
                value_type=ValueType.RASTER,
                unit="variable_specific",
                requirement_level=RequirementLevel.OPTIONAL,
                implementation_priority=ImplementationPriority.P1,
                accessibility=Accessibility.PROXY_ONLY,
                acquisition_modes=(AcquisitionMode.PUBLIC_DIRECT,),
                result_impact=ImpactLevel.MEDIUM,
                source_priority=("copernicus.era5_land",),
                quality_requirement=_quality(None, 9000, None, "valid_time", "accumulation_period"),
                missing_policies=(MissingPolicy.UNKNOWN,),
                used_by=(StageId.DATA_QUALITY_AND_DERIVE,),
            ),
            VariableSpec(
                variable_id="observation.dynamic_conditions",
                name_zh="动态地表状况观测",
                description="泥泞、积雪、积水、烟尘和施工等与任务时间相关的现场状态。",
                stage=StageId.DATA_ACQUIRE,
                data_role=DataRole.OBSERVATION,
                value_type=ValueType.OBJECT,
                unit=None,
                requirement_level=RequirementLevel.CONDITIONAL,
                required_when="规则集判定近期天气或变化可能显著改变地形效果时。",
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.PROXY_ONLY,
                acquisition_modes=(AcquisitionMode.LOCAL_OBSERVATION, AcquisitionMode.HYBRID),
                result_impact=ImpactLevel.HIGH,
                quality_requirement=_quality(None, None, 24, "observation_time", "source_reliability"),
                missing_policies=(MissingPolicy.PROXY, MissingPolicy.RECONNAISSANCE_REQUIRED, MissingPolicy.UNKNOWN),
                used_by=(StageId.ANALYSIS_OBSTACLES, StageId.ANALYSIS_COVER_AND_CONCEALMENT),
            ),
            VariableSpec(
                variable_id="observation.bridge_condition",
                name_zh="桥梁承载与状态观测",
                description="桥梁可用性、损毁和承载限制；公开地图标签通常不能可靠提供。",
                stage=StageId.DATA_ACQUIRE,
                data_role=DataRole.OBSERVATION,
                value_type=ValueType.OBJECT,
                unit=None,
                requirement_level=RequirementLevel.CONDITIONAL,
                required_when="候选路线必须使用桥梁或桥梁构成网络瓶颈时。",
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.UNAVAILABLE,
                acquisition_modes=(AcquisitionMode.LOCAL_OBSERVATION, AcquisitionMode.TASK_CONFIG),
                result_impact=ImpactLevel.HIGH,
                quality_requirement=_quality(None, None, 24, "asset_identity", "observation_time"),
                missing_policies=(MissingPolicy.RECONNAISSANCE_REQUIRED, MissingPolicy.UNKNOWN),
                used_by=(StageId.ANALYSIS_OBSTACLES, StageId.ANALYSIS_APPROACH_ROUTES),
            ),
            VariableSpec(
                variable_id="observation.water_state",
                name_zh="实时水文与渡越状态",
                description="任务时段的水深、流速、岸坡和河床状况。",
                stage=StageId.DATA_ACQUIRE,
                data_role=DataRole.OBSERVATION,
                value_type=ValueType.OBJECT,
                unit="mixed",
                requirement_level=RequirementLevel.CONDITIONAL,
                required_when="候选机动跨越河流、潮滩或其他水障碍时。",
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.UNAVAILABLE,
                acquisition_modes=(AcquisitionMode.LOCAL_OBSERVATION, AcquisitionMode.HYBRID),
                result_impact=ImpactLevel.HIGH,
                quality_requirement=_quality(None, None, 6, "observation_time", "measurement_method"),
                missing_policies=(MissingPolicy.RECONNAISSANCE_REQUIRED, MissingPolicy.UNKNOWN),
                used_by=(StageId.ANALYSIS_OBSTACLES, StageId.ANALYSIS_APPROACH_ROUTES),
            ),
            VariableSpec(
                variable_id="observation.local_visibility",
                name_zh="局地能见度观测",
                description="任务时间窗内雾、烟、降水等造成的局地实际能见距离。",
                stage=StageId.DATA_ACQUIRE,
                data_role=DataRole.OBSERVATION,
                value_type=ValueType.RASTER,
                unit="m",
                requirement_level=RequirementLevel.CONDITIONAL,
                required_when="输出实际探测效果而不仅是几何可视域时。",
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.PROXY_ONLY,
                acquisition_modes=(AcquisitionMode.LOCAL_OBSERVATION, AcquisitionMode.HYBRID),
                result_impact=ImpactLevel.HIGH,
                quality_requirement=_quality(None, None, 3, "observation_time", "measurement_method"),
                missing_policies=(MissingPolicy.PROXY, MissingPolicy.UNKNOWN),
                used_by=(StageId.ANALYSIS_OBSERVATION_AND_FIRE,),
            ),
        ]
    )

    # 第 3 至 5 步：统一原始数据的坐标、时间和单位，并记录覆盖和质量问题。
    variables.extend(
        [
            VariableSpec(
                variable_id="derived.normalized_data_stack",
                name_zh="时空语义统一数据栈",
                description="完成坐标、范围、时间、单位和分类映射后的资产引用集合。",
                stage=StageId.DATA_NORMALIZE,
                data_role=DataRole.DERIVED,
                value_type=ValueType.OBJECT,
                unit=None,
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.PUBLIC_DERIVED, AcquisitionMode.HYBRID),
                result_impact=ImpactLevel.HIGH,
                depends_on=("context.aoi", "context.time_window", "raster.elevation", "raster.land_cover"),
                derivation="按目标 CRS、AOI、时间窗和受控分类映射统一数据，不改变原始来源追踪。",
                quality_requirement=_quality(None, None, None, "crs_alignment", "time_alignment", "unit_alignment"),
                missing_policies=(MissingPolicy.MASK, MissingPolicy.BLOCK),
                used_by=(StageId.DATA_QUALITY_AND_DERIVE,),
            ),
            VariableSpec(
                variable_id="derived.data_coverage_mask",
                name_zh="数据覆盖状态掩膜",
                description="逐空间单元标记完整、部分、缺失或未知数据覆盖。",
                stage=StageId.DATA_NORMALIZE,
                data_role=DataRole.DERIVED,
                value_type=ValueType.RASTER,
                unit="status_code",
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.PUBLIC_DERIVED,),
                result_impact=ImpactLevel.HIGH,
                depends_on=("derived.normalized_data_stack",),
                derivation="合并各必要资产的空间覆盖、NoData 和时间有效性状态。",
                missing_policies=(MissingPolicy.BLOCK,),
                used_by=tuple(StageId)[3:],
            ),
            VariableSpec(
                variable_id="derived.slope",
                name_zh="坡度",
                description="由统一高程面计算的地表坡度，不直接等同于不可通行。",
                stage=StageId.DATA_QUALITY_AND_DERIVE,
                data_role=DataRole.DERIVED,
                value_type=ValueType.RASTER,
                unit="degree",
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.PUBLIC_DERIVED,),
                result_impact=ImpactLevel.HIGH,
                depends_on=("raster.elevation",),
                derivation="使用规则集指定的邻域和边界处理方法从 DEM 计算。",
                quality_requirement=_quality(None, 30, None, "edge_effect", "nodata_propagation"),
                missing_policies=(MissingPolicy.MASK, MissingPolicy.BLOCK),
                used_by=(StageId.BASELINE_BUILD, StageId.ANALYSIS_OBSTACLES),
            ),
            VariableSpec(
                variable_id="derived.aspect",
                name_zh="坡向",
                description="地表最大坡降方向，用于观察、光照或暴露相关辅助判断。",
                stage=StageId.DATA_QUALITY_AND_DERIVE,
                data_role=DataRole.DERIVED,
                value_type=ValueType.RASTER,
                unit="degree",
                requirement_level=RequirementLevel.OPTIONAL,
                implementation_priority=ImplementationPriority.P1,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.PUBLIC_DERIVED,),
                result_impact=ImpactLevel.LOW,
                depends_on=("raster.elevation",),
                derivation="与坡度使用相同 DEM 邻域和边界处理规则计算。",
                missing_policies=(MissingPolicy.UNKNOWN,),
                used_by=(StageId.ANALYSIS_OBSERVATION_AND_FIRE, StageId.ANALYSIS_COVER_AND_CONCEALMENT),
            ),
            VariableSpec(
                variable_id="derived.terrain_roughness",
                name_zh="地形起伏度",
                description="规则尺度内的高程变化指标，用于补充坡度无法表达的微起伏。",
                stage=StageId.DATA_QUALITY_AND_DERIVE,
                data_role=DataRole.DERIVED,
                value_type=ValueType.RASTER,
                unit="m_or_index",
                requirement_level=RequirementLevel.OPTIONAL,
                implementation_priority=ImplementationPriority.P1,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.PUBLIC_DERIVED,),
                result_impact=ImpactLevel.MEDIUM,
                depends_on=("raster.elevation",),
                derivation="按规则集指定窗口计算局地高程变化，输出必须记录窗口大小。",
                missing_policies=(MissingPolicy.UNKNOWN,),
                used_by=(StageId.ANALYSIS_OBSTACLES, StageId.ANALYSIS_COVER_AND_CONCEALMENT),
            ),
            VariableSpec(
                variable_id="derived.hydrologic_barriers",
                name_zh="水文障碍候选层",
                description="水系、水体历史和可用观测融合形成的潜在水障碍，不宣称实时不可通行。",
                stage=StageId.DATA_QUALITY_AND_DERIVE,
                data_role=DataRole.DERIVED,
                value_type=ValueType.OBJECT,
                unit=None,
                requirement_level=RequirementLevel.CONDITIONAL,
                required_when="AOI 内存在水体或水系证据时。",
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.HYBRID,),
                result_impact=ImpactLevel.HIGH,
                depends_on=("entity.hydrography", "raster.surface_water_history", "observation.water_state"),
                derivation="融合静态水系、历史水体和实时观测，并为缺少实时状态的对象保留 UNKNOWN。",
                missing_policies=(MissingPolicy.PROXY, MissingPolicy.RECONNAISSANCE_REQUIRED, MissingPolicy.UNKNOWN),
                used_by=(StageId.BASELINE_BUILD, StageId.ANALYSIS_OBSTACLES),
            ),
            VariableSpec(
                variable_id="derived.vegetation_density_proxy",
                name_zh="植被密度代理层",
                description="由土地覆盖和可用影像形成的植被存在或密度代理，不代表冠层结构。",
                stage=StageId.DATA_QUALITY_AND_DERIVE,
                data_role=DataRole.DERIVED,
                value_type=ValueType.RASTER,
                unit="index_or_class",
                requirement_level=RequirementLevel.OPTIONAL,
                implementation_priority=ImplementationPriority.P1,
                accessibility=Accessibility.PROXY_ONLY,
                acquisition_modes=(AcquisitionMode.PUBLIC_DERIVED,),
                result_impact=ImpactLevel.MEDIUM,
                depends_on=("raster.land_cover", "raster.optical_imagery"),
                derivation="依据规则集从覆盖类别和经过云掩膜的光学指标派生。",
                missing_policies=(MissingPolicy.PROXY, MissingPolicy.UNKNOWN),
                used_by=(StageId.ANALYSIS_OBSTACLES, StageId.ANALYSIS_COVER_AND_CONCEALMENT),
            ),
            VariableSpec(
                variable_id="derived.built_up_density",
                name_zh="建设区密度层",
                description="由建筑轮廓或土地覆盖形成的建设区密度代理。",
                stage=StageId.DATA_QUALITY_AND_DERIVE,
                data_role=DataRole.DERIVED,
                value_type=ValueType.RASTER,
                unit="ratio",
                requirement_level=RequirementLevel.OPTIONAL,
                implementation_priority=ImplementationPriority.P1,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.PUBLIC_DERIVED,),
                result_impact=ImpactLevel.MEDIUM,
                depends_on=("entity.buildings", "raster.land_cover"),
                derivation="优先栅格化建筑轮廓，缺失区域可用建设用地类别作低置信度代理。",
                missing_policies=(MissingPolicy.PROXY, MissingPolicy.UNKNOWN),
                used_by=(StageId.ANALYSIS_OBSERVATION_AND_FIRE, StageId.ANALYSIS_COVER_AND_CONCEALMENT),
            ),
            VariableSpec(
                variable_id="derived.surface_height_model",
                name_zh="表面高度模型",
                description="地形叠加可验证建筑或冠层高度后的遮挡表面；无法取得时只能退化为 DEM。",
                stage=StageId.DATA_QUALITY_AND_DERIVE,
                data_role=DataRole.DERIVED,
                value_type=ValueType.RASTER,
                unit="m",
                requirement_level=RequirementLevel.CONDITIONAL,
                required_when="请求包含建筑或植被遮挡的观察分析时。",
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.PROXY_ONLY,
                acquisition_modes=(AcquisitionMode.HYBRID,),
                result_impact=ImpactLevel.HIGH,
                depends_on=("raster.elevation", "entity.buildings"),
                derivation="仅叠加有来源的高度；缺失高度区域保留代理或退化标记。",
                missing_policies=(MissingPolicy.PROXY, MissingPolicy.UNKNOWN),
                used_by=(StageId.ANALYSIS_OBSERVATION_AND_FIRE,),
            ),
            VariableSpec(
                variable_id="derived.base_mobility_surface",
                name_zh="基础机动影响面",
                description="尚未绑定具体平台阈值的坡度、覆盖、水系和路网证据栈。",
                stage=StageId.DATA_QUALITY_AND_DERIVE,
                data_role=DataRole.DERIVED,
                value_type=ValueType.RASTER,
                unit="evidence_class",
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.HYBRID,),
                result_impact=ImpactLevel.HIGH,
                depends_on=("derived.slope", "raster.land_cover", "entity.transport_network", "derived.hydrologic_barriers"),
                derivation="对齐基础机动证据但不提前套用平台相关通行结论。",
                missing_policies=(MissingPolicy.MASK, MissingPolicy.UNKNOWN),
                used_by=(StageId.BASELINE_BUILD, StageId.ANALYSIS_OBSTACLES),
            ),
            VariableSpec(
                variable_id="result.data_quality_report",
                name_zh="数据质量报告",
                description="逐变量记录覆盖、分辨率、时效、来源和缺口的结构化报告。",
                stage=StageId.DATA_QUALITY_AND_DERIVE,
                data_role=DataRole.RESULT,
                value_type=ValueType.OBJECT,
                unit=None,
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.PUBLIC_DERIVED,),
                result_impact=ImpactLevel.HIGH,
                depends_on=("derived.normalized_data_stack", "derived.data_coverage_mask"),
                derivation="对每个 VariableBinding 执行其 QualityRequirement 并保留测量结果。",
                missing_policies=(MissingPolicy.BLOCK,),
                used_by=(StageId.BASELINE_BUILD, StageId.PUBLISH_VALIDATE_AND_RELEASE),
            ),
            VariableSpec(
                variable_id="result.analysis_baseline",
                name_zh="OAKOC 分析基线",
                description="包含公共地形派生层、来源追踪和质量状态的分析就绪数据包。",
                stage=StageId.BASELINE_BUILD,
                data_role=DataRole.RESULT,
                value_type=ValueType.OBJECT,
                unit=None,
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.HYBRID,),
                result_impact=ImpactLevel.HIGH,
                depends_on=("derived.normalized_data_stack", "result.data_quality_report"),
                derivation="组合通过质量检查的公共派生层和 UNKNOWN/MASK 区域，不填补无依据事实。",
                missing_policies=(MissingPolicy.BLOCK,),
                used_by=(
                    StageId.ANALYSIS_OBSTACLES,
                    StageId.ANALYSIS_OBSERVATION_AND_FIRE,
                    StageId.ANALYSIS_COVER_AND_CONCEALMENT,
                ),
            ),
            VariableSpec(
                variable_id="result.baseline_readiness",
                name_zh="分析就绪状态",
                description="逐分析节点给出的可执行、降级、不可用及其原因。",
                stage=StageId.BASELINE_BUILD,
                data_role=DataRole.RESULT,
                value_type=ValueType.OBJECT,
                unit=None,
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.PUBLIC_DERIVED,),
                result_impact=ImpactLevel.HIGH,
                depends_on=("result.data_quality_report",),
                derivation="根据本次必要变量、实际绑定状态和缺失策略判定。",
                missing_policies=(MissingPolicy.BLOCK,),
                used_by=tuple(StageId)[5:],
            ),
        ]
    )

    # 第 6 至 8 步：三项基础分析分别运行，每份结果都要说明适用主体、时间和规则版本。
    variables.extend(
        [
            VariableSpec(
                variable_id="result.obstacle_zones",
                name_zh="障碍影响区",
                description="相对于指定平台和时间条件形成的限制、阻滞或未知区域。",
                stage=StageId.ANALYSIS_OBSTACLES,
                data_role=DataRole.RESULT,
                value_type=ValueType.POLYGON,
                unit=None,
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.HYBRID,),
                result_impact=ImpactLevel.HIGH,
                depends_on=("result.analysis_baseline", "parameter.mobility_profile", "observation.dynamic_conditions"),
                derivation="按规则集将基础证据与平台能力组合，缺失动态状态的空间单元保持 UNKNOWN。",
                missing_policies=(MissingPolicy.MASK, MissingPolicy.UNKNOWN),
                used_by=(StageId.ANALYSIS_FOUNDATION_AGGREGATE, StageId.ANALYSIS_APPROACH_ROUTES),
            ),
            VariableSpec(
                variable_id="result.mobility_cost_surface",
                name_zh="机动成本面",
                description="针对平台和时间窗的相对通行成本，不表示绝对可通行保证。",
                stage=StageId.ANALYSIS_OBSTACLES,
                data_role=DataRole.RESULT,
                value_type=ValueType.RASTER,
                unit="relative_cost",
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.HYBRID,),
                result_impact=ImpactLevel.HIGH,
                depends_on=("derived.base_mobility_surface", "parameter.mobility_profile"),
                derivation="使用版本化平台规则映射证据并单独保留 UNKNOWN/MASK。",
                missing_policies=(MissingPolicy.MASK, MissingPolicy.UNKNOWN),
                used_by=(StageId.ANALYSIS_APPROACH_ROUTES,),
            ),
            VariableSpec(
                variable_id="result.mobility_restrictions",
                name_zh="机动限制与补采需求",
                description="桥梁、水文、临时障碍等无法确认内容及其路线影响。",
                stage=StageId.ANALYSIS_OBSTACLES,
                data_role=DataRole.RESULT,
                value_type=ValueType.ARRAY,
                unit=None,
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.HYBRID,),
                result_impact=ImpactLevel.HIGH,
                depends_on=("observation.bridge_condition", "observation.water_state"),
                derivation="把未绑定或过期的高影响观测转换为限制和侦察需求。",
                missing_policies=(MissingPolicy.UNKNOWN,),
                used_by=(StageId.ANALYSIS_FOUNDATION_AGGREGATE, StageId.ANALYSIS_APPROACH_ROUTES),
            ),
            VariableSpec(
                variable_id="result.viewshed",
                name_zh="几何可视域",
                description="给定观察位置、高度和表面模型下的几何通视区域。",
                stage=StageId.ANALYSIS_OBSERVATION_AND_FIRE,
                data_role=DataRole.RESULT,
                value_type=ValueType.RASTER,
                unit="visibility_class",
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.HYBRID,),
                result_impact=ImpactLevel.HIGH,
                depends_on=("derived.surface_height_model", "parameter.sensor_profile"),
                derivation="按规则集执行视线分析；DEM 退化结果必须标记未考虑建筑和冠层遮挡。",
                missing_policies=(MissingPolicy.PROXY, MissingPolicy.UNKNOWN),
                used_by=(StageId.ANALYSIS_FOUNDATION_AGGREGATE, StageId.ANALYSIS_KEY_TERRAIN_CANDIDATES),
            ),
            VariableSpec(
                variable_id="result.observation_gaps",
                name_zh="观察盲区与限制",
                description="几何遮挡、数据缺口和局地能见度限制共同形成的未知或低可见区域。",
                stage=StageId.ANALYSIS_OBSERVATION_AND_FIRE,
                data_role=DataRole.RESULT,
                value_type=ValueType.OBJECT,
                unit=None,
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.HYBRID,),
                result_impact=ImpactLevel.HIGH,
                depends_on=("result.viewshed", "observation.local_visibility", "derived.data_coverage_mask"),
                derivation="区分真实几何盲区、气象限制和数据未知区。",
                missing_policies=(MissingPolicy.UNKNOWN,),
                used_by=(StageId.ANALYSIS_FOUNDATION_AGGREGATE,),
            ),
            VariableSpec(
                variable_id="result.fire_coverage",
                name_zh="条件射界覆盖",
                description="在给定火力配置和几何条件下可能作用的区域，不表示实际火力效果。",
                stage=StageId.ANALYSIS_OBSERVATION_AND_FIRE,
                data_role=DataRole.RESULT,
                value_type=ValueType.RASTER,
                unit="coverage_class",
                requirement_level=RequirementLevel.CONDITIONAL,
                required_when="请求射界结果且已提供 fire_profile 时。",
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.HYBRID,),
                result_impact=ImpactLevel.HIGH,
                depends_on=("result.viewshed", "parameter.fire_profile"),
                derivation="根据版本化火力几何规则与地形视线求交，不推断未提供的能力参数。",
                missing_policies=(MissingPolicy.UNKNOWN,),
                used_by=(StageId.ANALYSIS_FOUNDATION_AGGREGATE, StageId.ANALYSIS_KEY_TERRAIN_CANDIDATES),
            ),
            VariableSpec(
                variable_id="result.fire_dead_zones",
                name_zh="射界死角与未知区",
                description="由地形遮挡、能力限制或输入缺失造成的不可覆盖与未知区域。",
                stage=StageId.ANALYSIS_OBSERVATION_AND_FIRE,
                data_role=DataRole.RESULT,
                value_type=ValueType.OBJECT,
                unit=None,
                requirement_level=RequirementLevel.CONDITIONAL,
                required_when="请求射界结果时。",
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.HYBRID,),
                result_impact=ImpactLevel.HIGH,
                depends_on=("result.fire_coverage", "derived.data_coverage_mask"),
                derivation="明确区分规则判定的死角与数据不足形成的 UNKNOWN。",
                missing_policies=(MissingPolicy.UNKNOWN,),
                used_by=(StageId.ANALYSIS_FOUNDATION_AGGREGATE,),
            ),
            VariableSpec(
                variable_id="result.cover_zones",
                name_zh="条件掩蔽区域",
                description="相对于给定威胁和证据强度可降低作用的区域。",
                stage=StageId.ANALYSIS_COVER_AND_CONCEALMENT,
                data_role=DataRole.RESULT,
                value_type=ValueType.POLYGON,
                unit=None,
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.PROXY_ONLY,
                acquisition_modes=(AcquisitionMode.HYBRID,),
                result_impact=ImpactLevel.HIGH,
                depends_on=("result.analysis_baseline", "parameter.fire_profile"),
                derivation="根据地形遮挡和已验证结构属性判断；缺少材料属性时不得宣称实际防护。",
                missing_policies=(MissingPolicy.PROXY, MissingPolicy.UNKNOWN),
                used_by=(StageId.ANALYSIS_FOUNDATION_AGGREGATE, StageId.ANALYSIS_KEY_TERRAIN_CANDIDATES),
            ),
            VariableSpec(
                variable_id="result.concealment_zones",
                name_zh="条件隐蔽区域",
                description="相对于指定观察传感器可能降低探测概率的区域。",
                stage=StageId.ANALYSIS_COVER_AND_CONCEALMENT,
                data_role=DataRole.RESULT,
                value_type=ValueType.POLYGON,
                unit=None,
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.PROXY_ONLY,
                acquisition_modes=(AcquisitionMode.HYBRID,),
                result_impact=ImpactLevel.HIGH,
                depends_on=("parameter.sensor_profile", "derived.vegetation_density_proxy", "derived.built_up_density"),
                derivation="按传感器和目标条件组合植被、建设区和几何遮挡代理。",
                missing_policies=(MissingPolicy.PROXY, MissingPolicy.UNKNOWN),
                used_by=(StageId.ANALYSIS_FOUNDATION_AGGREGATE, StageId.ANALYSIS_KEY_TERRAIN_CANDIDATES),
            ),
            VariableSpec(
                variable_id="result.exposure_surface",
                name_zh="暴露程度面",
                description="观察和作用威胁下的相对暴露指标，保留未知区域。",
                stage=StageId.ANALYSIS_COVER_AND_CONCEALMENT,
                data_role=DataRole.RESULT,
                value_type=ValueType.RASTER,
                unit="relative_index",
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.HYBRID,),
                result_impact=ImpactLevel.HIGH,
                depends_on=("result.viewshed", "result.cover_zones", "result.concealment_zones"),
                derivation="使用规则集汇总威胁相关结果，不把未知单元当作高暴露或低暴露。",
                missing_policies=(MissingPolicy.MASK, MissingPolicy.UNKNOWN),
                used_by=(StageId.ANALYSIS_FOUNDATION_AGGREGATE, StageId.ANALYSIS_APPROACH_ROUTES),
            ),
        ]
    )

    # 第 9 至 13 步：先汇总基础结果，再筛选候选、计算路线、确认关键地形并发布。
    variables.extend(
        [
            VariableSpec(
                variable_id="result.foundation_evidence_stack",
                name_zh="基础分析证据栈",
                description="障碍、观察射界和隐蔽掩蔽结果的统一引用与空间索引。",
                stage=StageId.ANALYSIS_FOUNDATION_AGGREGATE,
                data_role=DataRole.RESULT,
                value_type=ValueType.OBJECT,
                unit=None,
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.HYBRID,),
                result_impact=ImpactLevel.HIGH,
                depends_on=("result.obstacle_zones", "result.viewshed", "result.cover_zones", "result.concealment_zones"),
                derivation="统一结果范围、分辨率、状态和来源引用，不在汇聚时覆盖原始置信度。",
                missing_policies=(MissingPolicy.MASK, MissingPolicy.UNKNOWN),
                used_by=(StageId.ANALYSIS_KEY_TERRAIN_CANDIDATES, StageId.ANALYSIS_APPROACH_ROUTES),
            ),
            VariableSpec(
                variable_id="result.foundation_conflicts",
                name_zh="基础结果冲突清单",
                description="不同来源、时间或规则导致的空间证据冲突和处理状态。",
                stage=StageId.ANALYSIS_FOUNDATION_AGGREGATE,
                data_role=DataRole.RESULT,
                value_type=ValueType.ARRAY,
                unit=None,
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.HYBRID,),
                result_impact=ImpactLevel.MEDIUM,
                depends_on=("result.foundation_evidence_stack",),
                derivation="比较范围、时间、规则和状态，无法裁决的冲突保持开放。",
                missing_policies=(MissingPolicy.UNKNOWN,),
                used_by=(StageId.ANALYSIS_KEY_TERRAIN_CANDIDATES, StageId.PUBLISH_VALIDATE_AND_RELEASE),
            ),
            VariableSpec(
                variable_id="result.key_terrain_candidates",
                name_zh="候选关键地形",
                description="根据任务效果与基础地形证据识别、尚待路线复核的候选区域。",
                stage=StageId.ANALYSIS_KEY_TERRAIN_CANDIDATES,
                data_role=DataRole.RESULT,
                value_type=ValueType.POLYGON,
                unit=None,
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.HYBRID,),
                result_impact=ImpactLevel.HIGH,
                depends_on=("context.mission_objective", "context.effect_criteria", "result.foundation_evidence_stack"),
                derivation="按版本化规则形成候选和入选依据，不在路线分析前确认最终关键地形。",
                missing_policies=(MissingPolicy.UNKNOWN,),
                used_by=(StageId.ANALYSIS_APPROACH_ROUTES, StageId.ANALYSIS_KEY_TERRAIN_REVIEW),
            ),
            VariableSpec(
                variable_id="result.candidate_control_effects",
                name_zh="候选区域控制效果",
                description="候选区域对不同主体、任务效果和基础分析结果的条件影响。",
                stage=StageId.ANALYSIS_KEY_TERRAIN_CANDIDATES,
                data_role=DataRole.RESULT,
                value_type=ValueType.OBJECT,
                unit=None,
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.HYBRID,),
                result_impact=ImpactLevel.HIGH,
                depends_on=("result.key_terrain_candidates", "context.analysis_perspective"),
                derivation="逐候选记录适用主体、条件、证据和反事实影响。",
                missing_policies=(MissingPolicy.UNKNOWN,),
                used_by=(StageId.ANALYSIS_KEY_TERRAIN_REVIEW,),
            ),
            VariableSpec(
                variable_id="result.approach_routes",
                name_zh="候选接近路线",
                description="连接任务起终区域、满足已知约束的候选路线集合。",
                stage=StageId.ANALYSIS_APPROACH_ROUTES,
                data_role=DataRole.RESULT,
                value_type=ValueType.LINE,
                unit=None,
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.HYBRID,),
                result_impact=ImpactLevel.HIGH,
                depends_on=("context.route_terminals", "result.mobility_cost_surface", "result.exposure_surface", "result.key_terrain_candidates"),
                derivation="基于版本化成本规则生成多条候选路线，并保留穿越 UNKNOWN 区域的信息。",
                missing_policies=(MissingPolicy.MASK, MissingPolicy.UNKNOWN),
                used_by=(StageId.ANALYSIS_KEY_TERRAIN_REVIEW,),
            ),
            VariableSpec(
                variable_id="result.route_cost_profiles",
                name_zh="路线成本剖面",
                description="逐路线记录距离、机动、暴露、时间和数据未知成本。",
                stage=StageId.ANALYSIS_APPROACH_ROUTES,
                data_role=DataRole.RESULT,
                value_type=ValueType.ARRAY,
                unit="mixed",
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.HYBRID,),
                result_impact=ImpactLevel.HIGH,
                depends_on=("result.approach_routes",),
                derivation="按路线累计各已定义成本分量，禁止将 UNKNOWN 当作零成本。",
                missing_policies=(MissingPolicy.UNKNOWN,),
                used_by=(StageId.ANALYSIS_KEY_TERRAIN_REVIEW, StageId.PUBLISH_VALIDATE_AND_RELEASE),
            ),
            VariableSpec(
                variable_id="result.route_chokepoints",
                name_zh="路线瓶颈点",
                description="候选路线中替代性低、成本突变或依赖高影响未知变量的位置。",
                stage=StageId.ANALYSIS_APPROACH_ROUTES,
                data_role=DataRole.RESULT,
                value_type=ValueType.POINT,
                unit=None,
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.HYBRID,),
                result_impact=ImpactLevel.HIGH,
                depends_on=("result.approach_routes", "result.mobility_restrictions"),
                derivation="根据网络替代性、成本梯度和关键未知条件识别。",
                missing_policies=(MissingPolicy.UNKNOWN,),
                used_by=(StageId.ANALYSIS_KEY_TERRAIN_REVIEW,),
            ),
            VariableSpec(
                variable_id="result.route_windows",
                name_zh="路线有效时间窗",
                description="在当前数据和规则下路线满足已知条件的时间范围。",
                stage=StageId.ANALYSIS_APPROACH_ROUTES,
                data_role=DataRole.RESULT,
                value_type=ValueType.TIME_RANGE,
                unit=None,
                requirement_level=RequirementLevel.CONDITIONAL,
                required_when="路线受水文、天气、照明或任务时限影响时。",
                implementation_priority=ImplementationPriority.P1,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.HYBRID,),
                result_impact=ImpactLevel.MEDIUM,
                depends_on=("context.time_window", "observation.dynamic_conditions", "observation.water_state"),
                derivation="对有时间依据的限制求交；缺少动态数据时不生成虚假精确窗口。",
                missing_policies=(MissingPolicy.UNKNOWN, MissingPolicy.RECONNAISSANCE_REQUIRED),
                used_by=(StageId.ANALYSIS_KEY_TERRAIN_REVIEW, StageId.PUBLISH_VALIDATE_AND_RELEASE),
            ),
            VariableSpec(
                variable_id="result.key_terrain_review",
                name_zh="复核关键地形",
                description="结合候选控制效果、路线依赖和任务判据复核后的关键区域。",
                stage=StageId.ANALYSIS_KEY_TERRAIN_REVIEW,
                data_role=DataRole.RESULT,
                value_type=ValueType.POLYGON,
                unit=None,
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.HYBRID,),
                result_impact=ImpactLevel.HIGH,
                depends_on=("result.key_terrain_candidates", "result.approach_routes", "result.route_chokepoints"),
                derivation="逐候选检验任务效果、路线控制和替代性，保留未通过与无法确认原因。",
                missing_policies=(MissingPolicy.UNKNOWN,),
                used_by=(StageId.PUBLISH_VALIDATE_AND_RELEASE,),
            ),
            VariableSpec(
                variable_id="result.key_terrain_route_relevance",
                name_zh="关键地形路线相关性",
                description="复核区域对各候选路线的控制、支持、威胁和替代性关系。",
                stage=StageId.ANALYSIS_KEY_TERRAIN_REVIEW,
                data_role=DataRole.RESULT,
                value_type=ValueType.OBJECT,
                unit=None,
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.HYBRID,),
                result_impact=ImpactLevel.HIGH,
                depends_on=("result.key_terrain_review", "result.route_cost_profiles"),
                derivation="按路线逐项记录相关性证据，而不是只给出单一绝对标签。",
                missing_policies=(MissingPolicy.UNKNOWN,),
                used_by=(StageId.PUBLISH_VALIDATE_AND_RELEASE,),
            ),
            VariableSpec(
                variable_id="result.data_gap_report",
                name_zh="数据缺口与补采报告",
                description="必要变量缺失、空间掩膜、降级影响和补充观测需求清单。",
                stage=StageId.PUBLISH_VALIDATE_AND_RELEASE,
                data_role=DataRole.RESULT,
                value_type=ValueType.OBJECT,
                unit=None,
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.HYBRID,),
                result_impact=ImpactLevel.HIGH,
                depends_on=("result.data_quality_report", "result.foundation_conflicts"),
                derivation="汇总 VariableBinding、QualityAssessment、UNKNOWN 区域和阶段限制。",
                missing_policies=(MissingPolicy.BLOCK,),
                used_by=(StageId.PUBLISH_VALIDATE_AND_RELEASE,),
            ),
            VariableSpec(
                variable_id="result.map_products",
                name_zh="地图产品索引",
                description="各专题地图的文件、服务或图层引用及其适用范围。",
                stage=StageId.PUBLISH_VALIDATE_AND_RELEASE,
                data_role=DataRole.RESULT,
                value_type=ValueType.ARRAY,
                unit=None,
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.HYBRID,),
                result_impact=ImpactLevel.MEDIUM,
                depends_on=("result.key_terrain_review", "result.approach_routes"),
                derivation="渲染通过发布校验的结果并附范围、时间、规则和置信度。",
                missing_policies=(MissingPolicy.BLOCK,),
                used_by=(StageId.PUBLISH_VALIDATE_AND_RELEASE,),
            ),
            VariableSpec(
                variable_id="result.structured_package",
                name_zh="结构化结果包",
                description="包含基线、五项结果、来源、质量和规则版本的机器可读成果。",
                stage=StageId.PUBLISH_VALIDATE_AND_RELEASE,
                data_role=DataRole.RESULT,
                value_type=ValueType.OBJECT,
                unit=None,
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.HYBRID,),
                result_impact=ImpactLevel.HIGH,
                depends_on=("result.data_gap_report", "result.key_terrain_route_relevance"),
                derivation="按版本化发布 Schema 组装结果和完整追踪信息。",
                missing_policies=(MissingPolicy.BLOCK,),
                used_by=(StageId.PUBLISH_VALIDATE_AND_RELEASE,),
            ),
            VariableSpec(
                variable_id="result.analysis_conclusion",
                name_zh="综合分析结论",
                description="在明确主体、时间、规则、来源和限制条件下形成的综合说明。",
                stage=StageId.PUBLISH_VALIDATE_AND_RELEASE,
                data_role=DataRole.RESULT,
                value_type=ValueType.STRING,
                unit=None,
                requirement_level=RequirementLevel.REQUIRED,
                implementation_priority=ImplementationPriority.P0,
                accessibility=Accessibility.DERIVABLE,
                acquisition_modes=(AcquisitionMode.HYBRID,),
                result_impact=ImpactLevel.HIGH,
                depends_on=("result.structured_package", "result.data_gap_report"),
                derivation="只总结有证据支持的判断，并把降级、未知和适用范围写入结论。",
                missing_policies=(MissingPolicy.BLOCK,),
                used_by=(StageId.PUBLISH_VALIDATE_AND_RELEASE,),
            ),
        ]
    )
    # 返回元组表示调用方只能读取目录，不能意外增加或删除其中的变量。
    return tuple(variables)


def build_source_catalog() -> tuple[SourceSpec, ...]:
    """返回第一版考虑使用的公开来源，能力说明以 2026-09-02 的核实结果为准。"""

    # 所有来源使用同一个核实日期，后续复查来源时应分别更新实际日期。
    checked_on = date(2026, 9, 2)
    # 第一个来源完整展示 SourceSpec 字段，后面的公开来源使用相同含义：
    # source_id、provider、dataset 分别是来源编号、提供方和产品名称；
    # access_methods、discovery_url 说明怎样查询或下载；
    # coverage、resolution、temporal_coverage、update_frequency 说明空间和时间能力；
    # authentication、license 说明访问要求和使用条件；
    # provides 和 calculable_formats 说明能提供哪些变量以及程序可读取的格式；
    # limitations 和 fallback_source_ids 记录限制与备用来源；
    # adapter 是未来负责接入该来源的代码名称；verification_status、verified_on 和
    # verification_note 说明这些信息核实到了什么程度，不能代表接入代码已经完成。
    return (
        SourceSpec(
            source_id="copernicus.dem.glo30",
            provider="European Union / Copernicus Programme",
            dataset="Copernicus DEM GLO-30",
            access_methods=(AccessMethod.ODATA, AccessMethod.S3, AccessMethod.HTTPS),
            discovery_url="https://catalogue.dataspace.copernicus.eu/odata/v1/Products",
            coverage="Global land surface; actual tile coverage must be checked per AOI.",
            resolution="30 m posting for GLO-30.",
            temporal_coverage="Static product assembled from source acquisitions; use product edition metadata.",
            update_frequency="Versioned product, not a real-time elevation service.",
            authentication="Catalogue query is public; asset download method and credentials depend on CDSE access path.",
            license="Copernicus data terms and product-specific notice.",
            provides=("raster.elevation",),
            calculable_formats=("GeoTIFF", "DGED"),
            limitations=(
                "Represents terrain elevation and does not provide current buildings or vegetation height.",
                "Vertical reference, editing artefacts and local accuracy must be read from product metadata.",
            ),
            adapter="cdse_cop_dem_adapter",
            verification_status=VerificationStatus.PARTIAL,
            verified_on=checked_on,
            verification_note="CDSE OData catalogue endpoint responded successfully; exact GLO-30 collection filter and download flow remain adapter acceptance tests.",
        ),
        SourceSpec(
            source_id="esa.worldcover.2021",
            provider="European Space Agency",
            dataset="ESA WorldCover 2021 v200",
            access_methods=(AccessMethod.HTTPS,),
            discovery_url="https://esa-worldcover.org/en/data-access",
            coverage="Global land surface; tile-level AOI coverage must be verified.",
            resolution="10 m.",
            temporal_coverage="2021 product year.",
            update_frequency="Versioned annual product; not a live land-cover feed.",
            authentication="Official data access page is public; selected download path must be checked by adapter.",
            license="CC BY 4.0.",
            provides=("raster.land_cover",),
            calculable_formats=("Cloud Optimized GeoTIFF", "GeoTIFF"),
            limitations=(
                "Class labels do not provide canopy height, trunk spacing, soil strength or current damage.",
                "Product year may not represent recent local change.",
            ),
            adapter="esa_worldcover_adapter",
            verification_status=VerificationStatus.PARTIAL,
            verified_on=checked_on,
            verification_note="Official data-access page was reachable; tile-index details and machine download URLs remain adapter acceptance tests.",
        ),
        SourceSpec(
            source_id="copernicus.sentinel1.grd",
            provider="European Union / ESA",
            dataset="Sentinel-1 Ground Range Detected",
            access_methods=(AccessMethod.STAC, AccessMethod.ODATA, AccessMethod.S3),
            discovery_url="https://stac.dataspace.copernicus.eu/v1/collections/sentinel-1-grd",
            coverage="Global acquisition programme; scene availability varies by place and time.",
            resolution="Mode- and product-dependent; inspect each STAC item and asset.",
            temporal_coverage="From 2014-10-04 in the verified STAC collection metadata.",
            update_frequency="New acquisitions are added according to mission operations.",
            authentication="STAC discovery is public; HTTPS/S3 asset access declares OIDC or S3 authentication.",
            license="Copernicus Sentinel Data Legal Notice.",
            provides=("raster.sar_imagery",),
            calculable_formats=("SAFE", "GeoTIFF assets where exposed"),
            limitations=(
                "Backscatter requires calibration, terrain correction and interpretation before use.",
                "A change or low-backscatter signal is not by itself proof of flooding or obstacle state.",
            ),
            adapter="cdse_sentinel1_grd_adapter",
            verification_status=VerificationStatus.VERIFIED,
            verified_on=checked_on,
            verification_note="Official CDSE asset-level STAC collection, temporal extent and authentication declarations were read successfully.",
        ),
        SourceSpec(
            source_id="copernicus.sentinel2.l2a",
            provider="European Union / ESA",
            dataset="Sentinel-2 Level-2A Surface Reflectance",
            access_methods=(AccessMethod.STAC, AccessMethod.ODATA, AccessMethod.S3),
            discovery_url="https://stac.dataspace.copernicus.eu/v1/",
            coverage="Global land acquisition programme; scene and cloud-free availability vary.",
            resolution="10 m, 20 m and 60 m bands depending on spectral band.",
            temporal_coverage="Mission archive; exact collection extent must be read from current catalogue metadata.",
            update_frequency="New acquisitions are added according to mission operations.",
            authentication="STAC/OData discovery is public; asset download requires the current CDSE access flow.",
            license="Copernicus Sentinel Data Legal Notice.",
            provides=("raster.optical_imagery",),
            calculable_formats=("SAFE", "JPEG2000", "GeoTIFF assets where exposed"),
            limitations=(
                "Cloud, haze, shadow and revisit timing can prevent a usable observation for the task window.",
                "Spectral indices are proxies and require validation before operational interpretation.",
            ),
            adapter="cdse_sentinel2_l2a_adapter",
            verification_status=VerificationStatus.PARTIAL,
            verified_on=checked_on,
            verification_note="CDSE STAC and OData service roots were verified; exact current L2A collection ID and asset download acceptance test remain pending.",
        ),
        SourceSpec(
            source_id="osm.overpass",
            provider="OpenStreetMap contributors / public Overpass instance operators",
            dataset="OpenStreetMap current database subset",
            access_methods=(AccessMethod.OVERPASS,),
            discovery_url="https://overpass-api.de/api/interpreter",
            coverage="Global community-contributed coverage with strong regional variation.",
            resolution="Feature geometry and tags; no uniform spatial resolution.",
            temporal_coverage="Current database view at query time; element histories require other OSM services.",
            update_frequency="Continuously edited; public instance replication and load vary.",
            authentication="Public instances usually allow anonymous queries and impose resource limits.",
            license="Open Database License (ODbL) 1.0; attribution required.",
            provides=("entity.transport_network", "entity.buildings", "entity.hydrography"),
            calculable_formats=("OSM XML", "JSON", "GeoJSON after conversion"),
            limitations=(
                "Tag presence and completeness vary; missing tags do not mean a feature or property is absent.",
                "Public Overpass instances are unsuitable for unrestricted bulk extraction.",
            ),
            fallback_source_ids=("osm.geofabrik",),
            adapter="osm_overpass_adapter",
            verification_status=VerificationStatus.VERIFIED,
            verified_on=checked_on,
            verification_note="The public Overpass status endpoint responded; production must allow configurable instances and rate limits.",
        ),
        SourceSpec(
            source_id="osm.geofabrik",
            provider="Geofabrik GmbH / OpenStreetMap contributors",
            dataset="Regional OpenStreetMap extracts",
            access_methods=(AccessMethod.PBF_DOWNLOAD, AccessMethod.HTTPS),
            discovery_url="https://download.geofabrik.de/",
            coverage="Regional extracts for most countries and subregions listed by the provider.",
            resolution="Feature geometry and tags; no uniform spatial resolution.",
            temporal_coverage="Dated regional snapshots.",
            update_frequency="Typically daily; confirm the timestamp shown for each extract.",
            authentication="Public HTTPS download.",
            license="Open Database License (ODbL) 1.0; attribution required.",
            provides=("entity.transport_network", "entity.buildings", "entity.hydrography"),
            calculable_formats=("OSM PBF", "shapefile for selected layers"),
            limitations=(
                "Extract boundaries may not match the AOI and require clipping.",
                "Shares OpenStreetMap completeness and tagging limitations.",
            ),
            fallback_source_ids=("osm.overpass",),
            adapter="geofabrik_pbf_adapter",
            verification_status=VerificationStatus.PENDING,
            verified_on=checked_on,
            verification_note="Provider and access model are known, but the endpoint timed out from the current environment; re-verify before adapter acceptance.",
        ),
        SourceSpec(
            source_id="isric.soilgrids.2",
            provider="ISRIC - World Soil Information",
            dataset="SoilGrids 2.0",
            access_methods=(AccessMethod.REST, AccessMethod.WCS, AccessMethod.HTTPS),
            discovery_url="https://rest.isric.org/soilgrids/v2.0/docs",
            coverage="Global predictions for mapped soil areas; inspect NoData per property and depth.",
            resolution="250 m predictions.",
            temporal_coverage="Long-term modelled soil properties, not current surface condition.",
            update_frequency="Versioned model product; not a real-time service.",
            authentication="REST documentation is public; service limits and bulk-access route must be respected.",
            license="CC BY 4.0 with ISRIC data policy and citation requirements.",
            provides=("raster.soil_properties",),
            calculable_formats=("GeoTIFF", "GeoJSON point response", "WCS coverage"),
            limitations=(
                "REST properties/query returns point values and is not a substitute for bulk AOI download.",
                "Model uncertainty and 250 m resolution limit tactical-scale interpretation.",
                "Soil properties do not directly provide current trafficability or moisture state.",
            ),
            adapter="soilgrids_adapter",
            verification_status=VerificationStatus.PARTIAL,
            verified_on=checked_on,
            verification_note="Official REST OpenAPI exposed point query and property codes; WCS/bulk endpoint details still require acceptance testing.",
        ),
        SourceSpec(
            source_id="hydrosheds.hydrorivers",
            provider="HydroSHEDS / World Wildlife Fund",
            dataset="HydroRIVERS",
            access_methods=(AccessMethod.HTTPS,),
            discovery_url="https://www.hydrosheds.org/products/hydrorivers",
            coverage="Near-global river network derived from HydroSHEDS coverage.",
            resolution="Derived from 15 arc-second hydrography; suitable for regional context, not local channel geometry.",
            temporal_coverage="Static derived network product.",
            update_frequency="Versioned download product.",
            authentication="Official product page is public; download terms must be accepted where required.",
            license="HydroSHEDS licence and attribution terms; verify intended use before redistribution.",
            provides=("entity.hydrography",),
            calculable_formats=("shapefile", "geodatabase where offered"),
            limitations=(
                "Network scale is too coarse for tactical channel width, bank condition or crossing-site decisions.",
                "Does not provide task-time water depth, velocity or bed condition.",
            ),
            fallback_source_ids=("osm.overpass",),
            adapter="hydrorivers_adapter",
            verification_status=VerificationStatus.PARTIAL,
            verified_on=checked_on,
            verification_note="Official product page was reachable; exact regional package URL and licence acceptance flow remain adapter checks.",
        ),
        SourceSpec(
            source_id="jrc.global_surface_water",
            provider="European Commission Joint Research Centre",
            dataset="Global Surface Water",
            access_methods=(AccessMethod.HTTPS,),
            discovery_url="https://global-surface-water.appspot.com/download",
            coverage="Global Landsat-observed surface water coverage.",
            resolution="30 m.",
            temporal_coverage="1984-2021 for version 1.4 products.",
            update_frequency="Versioned historical product, not a live hydrology service.",
            authentication="Official downloads are public.",
            license="Copernicus free, full and open data policy; retain dataset citation and attribution.",
            provides=("raster.surface_water_history",),
            calculable_formats=("GeoTIFF",),
            limitations=(
                "Historical occurrence and seasonality do not provide current depth, flow or fordability.",
                "Observation gaps and classification uncertainty must be preserved.",
            ),
            adapter="jrc_surface_water_adapter",
            verification_status=VerificationStatus.PENDING,
            verified_on=checked_on,
            verification_note="Dataset properties are version-specific; official download host timed out in the current environment and must be re-verified before implementation.",
        ),
        SourceSpec(
            source_id="copernicus.era5_land",
            provider="Copernicus Climate Change Service / ECMWF",
            dataset="ERA5-Land hourly data from 1950 to present",
            access_methods=(AccessMethod.CDS_API, AccessMethod.HTTPS),
            discovery_url="https://cds.climate.copernicus.eu/datasets/reanalysis-era5-land",
            coverage="Global land grid.",
            resolution="0.1 degree native distribution grid, approximately 9 km.",
            temporal_coverage="1950 to present with production latency described by the dataset service.",
            update_frequency="Updated with the ERA5-Land production stream.",
            authentication="CDS account, dataset terms acceptance and API credentials are required for scripted retrieval.",
            license="Copernicus Climate Change Service licence and CDS terms.",
            provides=("raster.weather_fields",),
            calculable_formats=("GRIB", "NetCDF"),
            limitations=(
                "Grid spacing cannot represent tactical-scale local weather or visibility.",
                "Reanalysis values are modelled background fields and require temporal aggregation rules.",
            ),
            adapter="cds_era5_land_adapter",
            verification_status=VerificationStatus.VERIFIED,
            verified_on=checked_on,
            verification_note="Official CDS dataset page was reachable; account-specific API retrieval remains an integration test.",
        ),
    )
